### ISSUE TITLE
Enable Partners to submit charts

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/repo#10]
Three scenarios

- [ ] First submission requires manual approval #47 
   - [ ] Slack notification and email notification to the team when manual approval is required.

- [x] PR with chart and no report.
   - [x] Generate report as part of PR. 
   - [x] Chart is a directory
   - [x] Chart is a tarball
- [x] PR with report and no chart.
  - [x] ~Access chart from report uri. (This not required. The URL might be under firewall or required credentials)~
  - [x]   Validate URL 
- [x] PR with report and chart. (no need to run verifier. Publish the chart and use the same in the index.yaml)
   - [x] Chart is a directory
   - [x] Chart is a tarball

PR steps
- [x] Authenticate user (submitter of PR) #2 
- [x] Determine if community or partner (Red Hat?) submission.
       Ensure this extra annotation: `helm-chart.openshift.io/providerType` 
- [x] Set this extra annotation: `helm-chart.openshift.io/submissionTimestamp`
- [x] Ensure charts are stored in the correct folder #7
- [x] For partner if report provided  - ensure, report is GPG Signed #5
    - [x] ~make mandatory for partner charts~ ? (Decided not to make it mandatory)
- [x] Ensure checks all pass in verify report  #12 
  - [x] Only Mandatory checks - if failure fail PR.
- [ ] Ensure digest is same as chart (source) submitted (not possible with private hosted chart)
- [x] Read from verify report and add to index.yaml
   - [x] Annotations
   - [x] Values from chart.yaml 
- [x] Report outcome in github comments #8
   - [ ] Improve error messages #48
   - [ ] Update error message with link to partner support url #49
   - [ ] Capture PR details for issue analysis #50

Merge steps
- [x] Generate index.yaml entry #6 
   - [x] Include annotations for ODC 
- [x] If PR contains the chart tarball/sources, merge them to Red Hat Helm Repository, marking the submission as accepted 
- [x] ~On merge, update project status via API~ #9
- [x] if PR contains chart, publish chart as github release
   - [x]  Include report.yaml.
- [x] add chart entry to index.yaml that lives in gh-pages repo branch

see also: https://issues.redhat.com/browse/HELM-113

**Comment by baijum** [comment]
- [ ] Report should be passing with current schema?
- [ ] What is mandatory by the verifier tool itself?

**Comment by baijum** [comment]
Closing this ticker in favor of #61
